export interface InterviewExperience {
  id: number;
  company: string;
  role: string;
  experienceLevel: 'Beginner' | 'Intermediate' | 'Advanced';
  rounds: string[];
  questions: string[];
  tips: string[];
  date: string;
}

export const interviewExperiences: InterviewExperience[] = [
  {
    id: 1,
    company: 'Google',
    role: 'Software Engineer',
    experienceLevel: 'Advanced',
    rounds: ['Online Assessment', 'System Design', 'Behavioral'],
    questions: ['Design YouTube', 'Optimize database queries', 'Tell us about a time you failed'],
    tips: ['Practice LeetCode hard problems', 'Know system design patterns', 'Be honest about failures'],
    date: '2024-03-15',
  },
  {
    id: 2,
    company: 'Microsoft',
    role: 'Software Engineer',
    experienceLevel: 'Intermediate',
    rounds: ['Coding Round 1', 'Coding Round 2', 'Behavioral'],
    questions: ['Two Sum', 'Merge K Sorted Lists', 'Describe a challenging project'],
    tips: ['Focus on clean code', 'Ask clarifying questions', 'Communicate your approach'],
    date: '2024-03-10',
  },
  {
    id: 3,
    company: 'Amazon',
    role: 'Backend Engineer',
    experienceLevel: 'Advanced',
    rounds: ['OA', 'Technical Round 1', 'Technical Round 2', 'Bar Raiser'],
    questions: ['Design S3', 'LRU Cache', 'Distributed system design'],
    tips: ['Study AWS services', 'Prepare for LP questions', 'Think about scalability'],
    date: '2024-02-28',
  },
  {
    id: 4,
    company: 'Meta',
    role: 'Frontend Engineer',
    experienceLevel: 'Intermediate',
    rounds: ['Coding Round', 'System Design', 'Culture Fit'],
    questions: ['React component design', 'Build a chat interface', 'Why Meta?'],
    tips: ['Know React deeply', 'Prepare frontend system design', 'Be authentic'],
    date: '2024-03-05',
  },
  {
    id: 5,
    company: 'Apple',
    role: 'iOS Developer',
    experienceLevel: 'Advanced',
    rounds: ['Technical Interview 1', 'Technical Interview 2', 'Behavioral'],
    questions: ['Explain Swift protocols', 'Design an iOS app architecture', 'Leadership example'],
    tips: ['Know Swift language features', 'Practice iOS UI design', 'Highlight leadership'],
    date: '2024-02-20',
  },
  {
    id: 6,
    company: 'Netflix',
    role: 'Data Engineer',
    experienceLevel: 'Advanced',
    rounds: ['SQL Challenge', 'System Design', 'Behavioral'],
    questions: ['Complex SQL queries', 'Design recommendation engine', 'Handle conflict'],
    tips: ['Master SQL optimization', 'Know streaming architecture', 'Show ownership'],
    date: '2024-03-12',
  },
  {
    id: 7,
    company: 'LinkedIn',
    role: 'Software Engineer',
    experienceLevel: 'Intermediate',
    rounds: ['Coding Interview', 'System Design', 'Culture Fit'],
    questions: ['Array manipulation', 'Design feed algorithm', 'Motivations?'],
    tips: ['Practice medium difficulty problems', 'Think about scale', 'Research company'],
    date: '2024-03-08',
  },
  {
    id: 8,
    company: 'Uber',
    role: 'Backend Engineer',
    experienceLevel: 'Advanced',
    rounds: ['OA', 'Technical Round 1', 'Technical Round 2', 'Behavioral'],
    questions: ['Design Uber system', 'Distributed transactions', 'Team conflict resolution'],
    tips: ['Study geo-location algorithms', 'Know distributed systems', 'Be collaborative'],
    date: '2024-02-25',
  },
  {
    id: 9,
    company: 'Stripe',
    role: 'Software Engineer',
    experienceLevel: 'Advanced',
    rounds: ['Technical Round 1', 'Technical Round 2', 'System Design'],
    questions: ['Payment processing', 'API design', 'Handle large scale'],
    tips: ['Understand payment systems', 'Know API best practices', 'Think about security'],
    date: '2024-03-03',
  },
  {
    id: 10,
    company: 'Airbnb',
    role: 'Full Stack Engineer',
    experienceLevel: 'Intermediate',
    rounds: ['Coding Round', 'System Design', 'Behavioral'],
    questions: ['Build search feature', 'Design booking system', 'Collaboration story'],
    tips: ['Know full stack basics', 'Think user experience', 'Show teamwork'],
    date: '2024-02-18',
  },
  {
    id: 11,
    company: 'Shopify',
    role: 'DevOps Engineer',
    experienceLevel: 'Intermediate',
    rounds: ['Technical Interview', 'System Design', 'Culture Fit'],
    questions: ['Kubernetes setup', 'CI/CD pipeline design', 'Problem-solving?'],
    tips: ['Know Docker and Kubernetes', 'Understand deployment', 'Show learning mindset'],
    date: '2024-02-15',
  },
  {
    id: 12,
    company: 'Twilio',
    role: 'Software Engineer',
    experienceLevel: 'Beginner',
    rounds: ['Coding Round', 'Behavioral'],
    questions: ['String manipulation', 'Why Twilio?'],
    tips: ['Practice basic algorithms', 'Know company products', 'Be enthusiastic'],
    date: '2024-03-01',
  },
  {
    id: 13,
    company: 'Oracle',
    role: 'Database Engineer',
    experienceLevel: 'Advanced',
    rounds: ['SQL Interview', 'System Design', 'Behavioral'],
    questions: ['Complex queries', 'Design database', 'Technical leadership'],
    tips: ['Master SQL', 'Know database optimization', 'Show expertise'],
    date: '2024-02-22',
  },
  {
    id: 14,
    company: 'Canva',
    role: 'Frontend Engineer',
    experienceLevel: 'Intermediate',
    rounds: ['Coding Round', 'Design System', 'Behavioral'],
    questions: ['React optimization', 'Design UI component library', 'Growth mindset'],
    tips: ['Know React performance', 'Study design systems', 'Show creativity'],
    date: '2024-02-28',
  },
  {
    id: 15,
    company: 'Notion',
    role: 'Full Stack Engineer',
    experienceLevel: 'Advanced',
    rounds: ['Coding Round', 'System Design', 'Behavioral'],
    questions: ['Real-time collaboration', 'Design scalable DB', 'Team experience'],
    tips: ['Understand real-time systems', 'Know database design', 'Highlight achievements'],
    date: '2024-03-07',
  },
  {
    id: 16,
    company: 'Discord',
    role: 'Backend Engineer',
    experienceLevel: 'Advanced',
    rounds: ['OA', 'Technical Round', 'System Design'],
    questions: ['WebSocket architecture', 'Design message queue', 'Scale to millions'],
    tips: ['Know real-time systems', 'Understand scaling', 'Practice algorithms'],
    date: '2024-03-11',
  },
];

export const companies = Array.from(new Set(interviewExperiences.map((exp) => exp.company))).sort();
export const roles = Array.from(new Set(interviewExperiences.map((exp) => exp.role))).sort();
export const difficulties = ['Beginner', 'Intermediate', 'Advanced'];
